services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 3
    # volumes:
    #   - /Users/amolsingh/projects/click-stream-app/zookeeper_data:/var/lib/zookeeper/data
    #   - /Users/amolsingh/projects/click-stream-app/zookeeper_log:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_JMX_HOSTNAME: localhost
    # volumes:
    #   - /Users/amolsingh/projects/click-stream-app/kafka1_data:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_JMX_HOSTNAME: localhost
    # volumes:
    #   - /Users/amolsingh/projects/click-stream-app/kafka2_data:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    ports:
      - "9095:9095"
    expose:
      - "9095"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9095,OUTSIDE://localhost:9095
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29095,OUTSIDE://0.0.0.0:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_JMX_HOSTNAME: localhost
    # volumes:
    #   - /Users/amolsingh/projects/click-stream-app/kafka3_data:/var/lib/kafka/data

  init-kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    container_name: init-kafka
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' && \
        # sleep 10 && \
        # kafka-topics --bootstrap-server kafka1:29092 --list && \
        kafka-topics --create --bootstrap-server kafka1:29092 --topic click_stream_auth --partitions 3 --replication-factor 3 && \
        kafka-topics --create --bootstrap-server kafka1:29092 --topic click_stream_cart --partitions 3 --replication-factor 3 && \
        kafka-topics --create --bootstrap-server kafka1:29092 --topic click_stream_orders --partitions 3 --replication-factor 3 && \
        echo 'Topics created successfully!'
      "

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - /Users/amolsingh/projects/click-stream-app/db:/usr/src/app/db
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
      - init-kafka
